// Auto-generated by https://github.com/vladkens/apigen-ts
// Source: http://localhost:8000/openapi.json

export interface ApigenConfig {
  baseUrl: string;
  headers: Record<string, string>;
}

export interface ApigenRequest extends Omit<RequestInit, 'body'> {
  search?: Record<string, unknown>;
  body?: unknown;
}

export class ApiClient {
  Config: ApigenConfig;

  constructor(config?: Partial<ApigenConfig>) {
    this.Config = { baseUrl: '/', headers: {}, ...config };
  }

  async ParseError(rep: Response) {
    try {
      return await rep.json();
    } catch (e) {
      throw rep;
    }
  }

  PrepareFetchUrl(path: string): URL {
    let base = this.Config.baseUrl;
    if ('location' in globalThis && (base === '' || base.startsWith('/'))) {
      const { location } = globalThis as unknown as {
        location: { origin: string };
      };
      base = `${location.origin}${base.endsWith('/') ? base : `/${base}`}`;
    }

    return new URL(path, base);
  }

  async Fetch<T>(
    method: string,
    path: string,
    opts: ApigenRequest = {},
  ): Promise<T> {
    const url = this.PrepareFetchUrl(path);

    for (const [k, v] of Object.entries(opts?.search ?? {})) {
      url.searchParams.append(
        k,
        Array.isArray(v) ? v.join(',') : (v as string),
      );
    }

    const headers = new Headers({ ...this.Config.headers, ...opts.headers });
    const ct = headers.get('content-type') ?? 'application/json';

    let body: FormData | URLSearchParams | string | undefined = undefined;

    if (
      ct === 'multipart/form-data' ||
      ct === 'application/x-www-form-urlencoded'
    ) {
      headers.delete('content-type');
      body =
        ct === 'multipart/form-data' ? new FormData() : new URLSearchParams();
      for (const [k, v] of Object.entries(
        opts.body as Record<string, string>,
      )) {
        body.append(k, v);
      }
    }

    if (ct === 'application/json' && typeof opts.body !== 'string') {
      headers.set('content-type', 'application/json');
      body = JSON.stringify(opts.body);
    }

    const credentials = opts.credentials ?? 'include';
    const rep = await fetch(url.toString(), {
      method,
      ...opts,
      headers,
      body,
      credentials,
    });
    if (!rep.ok) throw await this.ParseError(rep);

    const rs = await rep.text();
    try {
      return JSON.parse(rs) as T;
    } catch (e) {
      return rs as unknown as T;
    }
  }

  apiGETEndpoints = {
    getBackhaulDataApiBackhaulGet: () => {
      return this.Fetch<BackhaulDetail[]>('get', '/api/backhaul', {});
    },

    getCountryDataApiCountriesGet: () => {
      return this.Fetch<CountriesResponse>('get', '/api/countries', {});
    },

    getPowerDataApiPowerGet: () => {
      return this.Fetch<PowerResponse>('get', '/api/power', {});
    },

    getLanguagesDataApiLanguagesGet: () => {
      return this.Fetch<LanguagesResponse>('get', '/api/languages', {});
    },

    getSiteTextByLangApiSiteTextGet: (search: { lang?: string }) => {
      return this.Fetch<SiteTextResponse>('get', '/api/site_text', { search });
    },

    getDefaultsDataApiDefaultsGet: () => {
      return this.Fetch<DefaultsDetail[]>('get', '/api/defaults', {});
    },

    getFrequenciesDataApiFrequenciesGet: () => {
      return this.Fetch<FrequencyDetail[]>('get', '/api/frequencies', {});
    },

    getMidhaulDataApiMidhaulGet: () => {
      return this.Fetch<MidhaulDetail[]>('get', '/api/midhaul', {});
    },

    getNetworkDataApiNetworksGet: () => {
      return this.Fetch<unknown[]>('get', '/api/networks', {});
    },

    getNetworkTypeDataApiNetworkTypesGet: () => {
      return this.Fetch<unknown[]>('get', '/api/network_types', {});
    },

    getSolarDataApiSolarDataGet: () => {
      return this.Fetch<unknown>('get', '/api/solar_data', {});
    },

    getTechnologyDataApiTechnologiesGet: () => {
      return this.Fetch<TechnologyDetail[]>('get', '/api/technologies', {});
    },

    getTerrainDataApiTerrainGet: () => {
      return this.Fetch<unknown>('get', '/api/terrain', {});
    },

    getTowerDataApiTowersGet: () => {
      return this.Fetch<unknown>('get', '/api/towers', {});
    },

    getVegetationDataApiVegetationGet: () => {
      return this.Fetch<unknown>('get', '/api/vegetation', {});
    },

    getCharacteristicsGetApiCharacteristicsIso3Get: (iso_3: string) => {
      return this.Fetch<DefaultsDetail[]>(
        'get',
        `/api/characteristics/${iso_3}`,
        {},
      );
    },
  };

  maintenanceTools = {
    getSolarDataApiRefreshGet: () => {
      return this.Fetch<unknown>('get', '/api/refresh', {});
    },
  };

  apiPOSTEndpoints = {
    receiveDataApiFilterPost: (body: FrequencyData) => {
      return this.Fetch<FrequencyResponse[]>('post', '/api/filter', { body });
    },

    getCharacteristicsApiCharacteristicsPost: (
      body: CharacteristicsRequest,
    ) => {
      return this.Fetch<DefaultsDetail[]>('post', '/api/characteristics', {
        body,
      });
    },

    modelerApiApiModelerPost: (body: BuilderInput) => {
      return this.Fetch<ModelerAPIOutput>('post', '/api/modeler', { body });
    },
  };

  general = {
    postHandlerPost: (body: Body_post_handler__post) => {
      return this.Fetch<unknown>('post', '/', {
        body,
        headers: { 'content-type': 'application/x-www-form-urlencoded' },
      });
    },

    spaPostHandlerSpaQueryPost: (body: ModelQuery) => {
      return this.Fetch<unknown>('post', '/spa-query', { body });
    },
  };
}

export type BackhaulDetail = {
  name: string;
  type: string;
  speed_mbps: number;
  power_watts: number;
  capital_cost_usd: number;
  cost_base: number;
  cost_mbps: number;
  element: string;
};

export type Body_post_handler__post = {
  selected_country: string;
  lang?: string;
};

export type BuilderInput = {
  area_sqkm: number;
  battery_age_derating: number;
  battery_cost_watt_hour: number;
  battery_dod?: number | null;
  charger_inverter_base: number;
  charger_inverter_variable: number;
  iso_3: string;
  labour_cost: number;
  lang?: string | null;
  locations: LocationData[];
  mains_power_cost_kwh: number;
  mains_power_installation_cost: number;
  power_hybrid_hours?: number | null;
  power_intermittent_hours?: number | null;
  power_reliable_hours?: number | null;
  solar_cost_watt: number;
  solar_derating: number;
  solar_efficiency: number;
  system_life: number;
  terrain_type: string;
  total_potential_users: number;
  traffic_growth: number;
  users_per_household: number;
  vegetation_type: string;
  year_1_traffic: number;
  households_total?: number | null;
  hh_size?: number | null;
  pop_growth_rate?: number | null;
  hh_income_week?: number | null;
  businesses?: number | null;
  business_users?: number | null;
  service_providers?: number | null;
  service_provider_users?: number | null;
  staff_opex_fixed?: number | null;
  staff_opex_variable?: number | null;
  maintenance_opex?: number | null;
  capex_subsidy?: number | null;
  opex_subsidy?: number | null;
  ue_subsidy?: number | null;
  finance_cost?: number | null;
  debt_proportion?: number | null;
  wacc?: number | null;
  corp_tax?: number | null;
  spectrum_licence_fee?: number | null;
  other_opex?: number | null;
  oc_margin?: number | null;
  community_capex_discount?: number | null;
  paf_deterred_use?: number | null;
  paf_sub_use?: number | null;
  paf_non_sub_use?: number | null;
  paf_gb_hour?: number | null;
  paf_facilities_charge?: number | null;
  paf_usd_hour?: number | null;
  ue_cost?: number | null;
  inflation?: number | null;
  power_offgrid_hours?: number | null;
  provider_type?: string | null;
  existing_ue_above_med?: number | null;
  existing_ue_below_med?: number | null;
};

export type CharacteristicsRequest = {
  iso_3: string;
};

export type CountriesResponse = object;

export type DefaultsDetail = {
  variable: string;
  value: number;
  min: number;
  max: number;
  step: number;
  element: string;
  unit: string;
  alt: number;
  category: string;
  seq: number;
  noDefault?: boolean | null;
};

export type FrequencyData = {
  frequencies: number[];
  technologies?: string[] | null;
};

export type FrequencyDetail = {
  frequency: number;
  frequency_name: string;
};

export type FrequencyResponse = {
  frequency: number;
  network_types: string[];
};

export type HTTPValidationError = {
  detail?: ValidationError[];
};

export type LanguagesResponse = object;

export type LocationData = {
  location_name: string;
  tower_cost: number | null;
  network_type: string[];
  sectors: number[];
  network_links: string[];
  backhaul_links: string[];
  backhaul_cost_base: number[] | null;
  backhaul_cost_mbps: number[] | null;
  power_type: string | null;
};

export type MidhaulDetail = {
  name: string;
  speed_mbps: number;
  capital_cost_usd: number;
  power_watts: number;
  element: string;
};

export type ModelQuery = {
  iso_3: string;
  lang: string;
};

export type ModelerAPIOutput = {
  detailed_results: object[];
  demand_curve_points?: object[];
  dcba_table_rows?: object[] | null;
  dcba_table_columns?: object[] | null;
  pl_table_rows?: object[] | null;
  pl_table_columns?: object[] | null;
  inv_table_rows?: object[] | null;
  inv_table_columns?: object[] | null;
  outcomes_table_rows?: object[] | null;
  outcomes_table_columns?: object[] | null;
  net_summary_table_rows?: object[] | null;
  net_summary_table_columns?: object[] | null;
};

export type PowerItem = {
  element: string;
  description: string;
};

export type PowerResponse = PowerItem[];

export type SiteTextResponse = object;

export type TechnologyDetail = {
  technology: string;
  technology_name: string;
};

export type ValidationError = {
  loc: (string | number)[];
  msg: string;
  type: string;
};
