// Generated by ts-to-zod
import { z } from "zod";

export const apigenConfigSchema = z.object({
    baseUrl: z.string(),
    headers: z.record(z.string(), z.string())
});

export const backhaulDetailSchema = z.object({
    name: z.string(),
    type: z.string(),
    speed_mbps: z.number(),
    power_watts: z.number(),
    capital_cost_usd: z.number(),
    cost_base: z.number(),
    cost_mbps: z.number(),
    element: z.string()
});

export const bodyPostHandlerPostSchema = z.object({
    selected_country: z.string(),
    lang: z.string().optional()
});

export const locationDataSchema = z.object({
    location_name: z.string(),
    tower_cost: z.number().nullable(),
    network_type: z.array(z.string()),
    sectors: z.array(z.number()),
    network_links: z.array(z.string()),
    backhaul_links: z.array(z.string()),
    backhaul_cost_base: z.array(z.number()).nullable(),
    backhaul_cost_mbps: z.array(z.number()).nullable(),
    power_type: z.string().nullable()
});

export const characteristicsRequestSchema = z.object({
    iso_3: z.string()
});

export const countriesResponseSchema = z.record(z.string(), z.any());

export const defaultsDetailSchema = z.object({
    variable: z.string(),
    value: z.number(),
    min: z.number(),
    max: z.number(),
    step: z.number(),
    element: z.string(),
    unit: z.string(),
    alt: z.number(),
    category: z.string(),
    seq: z.number(),
    noDefault: z.boolean().optional().nullable()
});

export const frequencyDataSchema = z.object({
    frequencies: z.array(z.number()),
    technologies: z.array(z.string()).optional().nullable()
});

export const frequencyDetailSchema = z.object({
    frequency: z.number(),
    frequency_name: z.string()
});

export const frequencyResponseSchema = z.object({
    frequency: z.number(),
    network_types: z.array(z.string())
});

export const validationErrorSchema = z.object({
    loc: z.array(z.union([z.string(), z.number()])),
    msg: z.string(),
    type: z.string()
});

export const languagesResponseSchema = z.record(z.string(), z.any());

export const midhaulDetailSchema = z.object({
    name: z.string(),
    speed_mbps: z.number(),
    capital_cost_usd: z.number(),
    power_watts: z.number(),
    element: z.string()
});

export const modelQuerySchema = z.object({
    iso_3: z.string(),
    lang: z.string()
});

export const modelerApiOutputSchema = z.object({
    detailed_results: z.array(z.record(z.string(), z.any())),
    demand_curve_points: z.array(z.record(z.string(), z.any())).optional(),
    dcba_table_rows: z.array(z.record(z.string(), z.any())).optional().nullable(),
    dcba_table_columns: z.array(z.record(z.string(), z.any())).optional().nullable(),
    pl_table_rows: z.array(z.record(z.string(), z.any())).optional().nullable(),
    pl_table_columns: z.array(z.record(z.string(), z.any())).optional().nullable(),
    inv_table_rows: z.array(z.record(z.string(), z.any())).optional().nullable(),
    inv_table_columns: z.array(z.record(z.string(), z.any())).optional().nullable(),
    outcomes_table_rows: z.array(z.record(z.string(), z.any())).optional().nullable(),
    outcomes_table_columns: z.array(z.record(z.string(), z.any())).optional().nullable(),
    net_summary_table_rows: z.array(z.record(z.string(), z.any())).optional().nullable(),
    net_summary_table_columns: z.array(z.record(z.string(), z.any())).optional().nullable()
});

export const powerItemSchema = z.object({
    element: z.string(),
    description: z.string()
});

export const powerResponseSchema = z.array(powerItemSchema);

export const siteTextResponseSchema = z.record(z.string(), z.any());

export const technologyDetailSchema = z.object({
    technology: z.string(),
    technology_name: z.string()
});

export const builderInputSchema = z.object({
    area_sqkm: z.number(),
    battery_age_derating: z.number(),
    battery_cost_watt_hour: z.number(),
    battery_dod: z.number(),
    charger_inverter_base: z.number(),
    charger_inverter_variable: z.number(),
    iso_3: z.string(),
    labour_cost: z.number(),
    lang: z.string().optional().nullable(),
    locations: z.array(locationDataSchema),
    mains_power_cost_kwh: z.number(),
    mains_power_installation_cost: z.number(),
    power_hybrid_hours: z.number(),
    power_intermittent_hours: z.number(),
    power_reliable_hours: z.number(),
    solar_cost_watt: z.number(),
    solar_derating: z.number(),
    solar_efficiency: z.number(),
    system_life: z.number(),
    terrain_type: z.string().optional().nullable(),
    total_potential_users: z.number(),
    traffic_growth: z.number(),
    users_per_household: z.number(),
    vegetation_type: z.string().optional().nullable(),
    year_1_traffic: z.number(),
    households_total: z.number().optional().nullable(),
    hh_size: z.number().optional().nullable(),
    pop_growth_rate: z.number().optional().nullable(),
    hh_income_week: z.number(),
    businesses: z.number().optional().nullable(),
    business_users: z.number().optional().nullable(),
    service_providers: z.number().optional().nullable(),
    service_provider_users: z.number().optional().nullable(),
    staff_opex_fixed: z.number(),
    staff_opex_variable: z.number(),
    maintenance_opex: z.number().optional().nullable(),
    capex_subsidy: z.number().optional().nullable(),
    opex_subsidy: z.number().optional().nullable(),
    ue_subsidy: z.number().optional().nullable(),
    finance_cost: z.number().optional().nullable(),
    debt_proportion: z.number().optional().nullable(),
    wacc: z.number(),
    corp_tax: z.number().optional().nullable(),
    spectrum_licence_fee: z.number(),
    other_opex: z.number().optional().nullable(),
    oc_margin: z.number().optional().nullable(),
    community_capex_discount: z.number(),
    paf_deterred_use: z.number().optional().nullable(),
    paf_sub_use: z.number().optional().nullable(),
    paf_non_sub_use: z.number().optional().nullable(),
    paf_gb_hour: z.number().optional().nullable(),
    paf_facilities_charge: z.number().optional().nullable(),
    paf_usd_hour: z.number().optional().nullable(),
    ue_cost: z.number().optional().nullable(),
    inflation: z.number(),
    power_offgrid_hours: z.number().optional().nullable(),
    provider_type: z.string().optional().nullable(),
    existing_ue_above_med: z.number().optional().nullable(),
    existing_ue_below_med: z.number().optional().nullable()
});

export const httpValidationErrorSchema = z.object({
    detail: z.array(validationErrorSchema).optional()
});
